### ISSUE TITLE
Remove old unnecessary files

### ISSUE THREAD

**Issue by watkipet** [hoche/splat#13]
Since the advent of the CMake build system (#4), some of the existing files are obsolete:

1. `vstudio` - Can now be generated using `cmake -G "Visual Studio 15 2017 Win64"`
2. `install` - After running cmake, you can now just run `make install`
3. `README` - Any reason this information can't be merged into `README.md`?
4. `Makefile` - Now generated by cmake
5. `utils\Makefile` - Now generated by cmake
6. `utils\install` - After running cmake, you can now just run `make install`
7. Subfolders under `docs\*` - The cmake build system automatically generates the `.txt`, `.pdf`, `.ps` and man-page outputs from `splat.man`

Any reason to keep what I've listed above? Is there anything else I should remove?

**Comment by der-stefan** [comment]
Great! Feel free to through the old ballast over board... 😃

**Comment by hoche** [comment]
I'm fine with removing all of those, and merging what little of the README that's still relevant into the README.md.

**Comment by watkipet** [comment]
OK. I think this is finished. I did most of the work on [iss13](https://github.com/hoche/splat/tree/iss13) and merged that branch back to refactor.
