### ISSUE TITLE
Break backward compatibility

### ISSUE THREAD

**Issue by der-stefan** [hoche/splat#21]
Dear folks,

after having hands-on at Splat! and considering myself as being still somehow unbiased, I would suggest to change a few things in future 2.0 release that will break backward compatibility:

- Give all parameters in SI units as default. That includes: lengths/heights in meter, ~~frequency in Hz (but e.g. with correct parsing of 433M or 1.8G)~~ _freq in MHz should be fine_
- Use standard geographical coordinates. The zero meridian goes through Greenwich. Eastern is positive, Western negative longitude. Alternatively, parse 122.4192W correctly, if Americans have a strong feeling about "negative" coordinates.
- Abolish annotated map for coverage predictions. The technical possibilities changed during the last 20 years and a georeferenced image can be easily loaded into web maps or offline GIS nowadays. (Wait for my work done in #5...)
- Abolish in-picture legend.
- Abolish "-hd" option. Nowadays, a global 30m DEM is standard and the old resolution of 90m is superseded.
- Abolish "-sdelim" and just use "_" as default delimiter. Or even better: read geotiff DEMs.
- Rename "-c" to "-los" as this calculates a line of sight coverage.
- Rename "-L" to "-radio" as this calculates a radio propagation coverage.
- Use EIRP instead of ERP - or just TX power and antenna pattern? (see #24).
- Use logarithmic antenna pattern instead of normalized voltage (!) radiation patterns (see #24).

Please consider my thoughts as proposals only. It's just a good time to reconsider the status quo. I won't break up with Splat! if you have different plans. 😃 

Please also note that I will edit and add items from the list above in the future.

**Comment by davidsrsb** [comment]
Basically I agree with these.
As always be careful to test around the Equator and the International Date Line.
I await an easier way of importing a georeferenced layer into QGIS, hacking a .pgw file is a pain

**Comment by hoche** [comment]
I agree with all of these as well.

The -hd option can certainly go away. I only added it to stay backwards compatible. With the dynamic memory allocations and modern system RAM amounts, it really shouldn't be necessary.

It should be able to parse any of several lat/long formats. +/- or E/W. "DDD MM SS.S", or "DD MM.MMM", or "DDD.DDDDDD", etc., And yeah, Greenwich is 0.

**Comment by davidsrsb** [comment]
I disagree about dropping "-hd" as the 30m data is substandard compared with the 90m in many areas

**Comment by der-stefan** [comment]
> I disagree about dropping "-hd" as the 30m data is substandard compared with the 90m in many areas

Are you sure? My experience from OpenTopoMap is different. The standard SRTM30 is already void-filled. If you perfer a somehow differently processed dataset, you can use the new NASADEM. Then there are EU-DEM for Europe, or the brandnew AW3D30 v3.1 from the Japanese ALOS mission... Great days for remote sensing people... 😁

**Comment by davidsrsb** [comment]
I am based in Malaysia, so I am interested in SE Asia and the ME.
Maybe because the Shuttle 1 arc-second DEM was not available outside the US and the 3 arc-second was the best available, it has had more cleaning up. The 3x3 averaging must have cleaned a lot of noise.
This date is 20 years old now, and development has made it increasingly inaccurate
Thanks for the info on the AW3D30 v3.1

**Comment by der-stefan** [comment]
Anyway, both 30m and 90m DEMs must be handled by SPLAT. It's just the question which mode should be default. @hoche did a great job with dynamic memory allocation (malloc) what makes the software future-proof for even better DEMs.

I am still not sure how to proceed the version 2.0 development, as I currenlty use and test the coverage prediction output. Of course we want to keep the other modes and simply purify outdated functionality.

**Comment by dBitech** [comment]
my preference would be to use the highest res data as the default,

**Comment by watkipet** [comment]
What about putting these changes into a 2.0 branch? We already have a 1.5 branch which is mostly backwards compatible. But if I were a user, I would be less confused by a 2.0 version not being backwards compatible. Then, for this repository, I would hope that 2.0 would eventually become the master. If absolutely necessary, we could backport bug fixes to the 1.5 branch.

**Comment by hoche** [comment]
I would prefer to keep the 1.5 branch as backwards-compatible as possible. I don't mind adding new flags to it, but older flags should still work as expec...er, as in previous experiences. We've already gone a little off the rails there a little (I'm certainly guilty of that and changing some defaults) but lets keep those sorts of changes to a minimum.

2.0...yeah, we can change that. I expect we'll have some iterations of the flags as go along adding features and fixing things.

**Comment by der-stefan** [comment]
Yeah, I think it is a good idea to keep 1.5 backwards-compatible. However, I am strongly interested in a 2.0 branch with tons of new features and metric/ISO conventions and am willing to contribute here. Maintaining the 1.5 branch could be accomplished by carefully taking over features from the 2.0 branch - with the main development happening there.

A good starting point would be to rename the "json" branch to "2.0-alpha", to get rid of my json fragments and to restart a json branch just for json features... 🤣 Do you agree with this approach?

**Comment by watkipet** [comment]
@der-stefan and @hoche -- `json` was branched from `refactor` which was branched from `1.5`, maybe? We don't need the refactor branch anymore. Mind if I merge `json` into `refactor` and then rename `refactor` to `2.0-alpha`?

**Comment by der-stefan** [comment]
Yes, I would appreciate if you tackle the branch cleanups. Let's keep the number of branches short for clarity.

**Comment by hoche** [comment]
Sounds good to me!

**Comment by watkipet** [comment]
OK. [Renamed](https://stackoverflow.com/questions/9524933/renaming-a-branch-in-github) the refactor branch to the `2.0-alpha` branch. Closing this. I think we should open individual issues for the 2.0 milestone instead of one large one (as this one is).
