### ISSUE TITLE
Add support for CMake

### ISSUE THREAD

**Issue by watkipet** [hoche/splat#4]
This task is to add CMake support to the `refactor` branch  (or a branch off of that one).

**Comment by der-stefan** [comment]
I am new to CMake, but it doesn't look very complicated. Basically only one or more CMakeLists.txt must be written. 
I created a 12-liner based on the first step of the offical cmake guide (https://cmake.org/cmake/help/latest/guide/tutorial/index.html).

https://github.com/der-stefan/splat/blob/cleanup/CMakeLists.txt

The normal procedure for building is:
```
cd build
cmake ..
make
```

**Comment by watkipet** [comment]
@der-stefan - Cool! I migrated my CMake files from my own repo with some modifications to match the directory structure you proposed in #6. It's under the branch [iss4](https://github.com/hoche/splat/tree/iss4). It still doesn't build yet. I still need to add some support for the later version of C++ @hoche is using (as you did). I'll move over some of what you put in your CMakeLists.txt that you linked to.

**Comment by watkipet** [comment]
@hoche and @der-stefan - Branch iss4 should build now with cmake (though I broke the regular makefile in the process--I'll work on fixing that). I also still need to move headers to a headers directory.

**Comment by hoche** [comment]
I wouldn't worry about the regular Makefile too much at this point. I just started modularizing the code and I'm using the regular Makefile for doing that, but I consider it to be only temporary until you get the CMakefiles and directory structure in order. At any rate, I got a couple of files done tonight; I'll work on the Paths and DEMs tomorrow.

**Comment by watkipet** [comment]
I think I've done the initial work with help from @hoche and @der-stefan. I'm closing this. Feel free to re-open if something is missing.

**Comment by hoche** [comment]
Can we delete the iss4 branch?

**Comment by watkipet** [comment]
Yes. Same with the other closed issue branches. Want me to go ahead and delete them when I’m done from now on?

**Comment by hoche** [comment]
Yeah, I think whoever merges them can delete them when done.
