### ISSUE TITLE
Improve codebase for JSON input and output for multi-purpose usage

### ISSUE THREAD

**Issue by der-stefan** [hoche/splat#5]
_edit notice: The primary goal of having a JSON output file for georeferencing PNG images is now superseded by the idea of a multi-purpose input/output functionality. The discussion below develops accordingly._

An interactive map that shows the coverage simulations is a useful feature. Splat will generate a HTML file that can be opened locally and just adds a Leaflet map with various OpenStreetMap tiles as background.
Further requirements:
- The output must be PNG, JPEG or GeoTIFF
- An additional json file is written that includes the simulation parameters (qth, lrp) and the extent of the image for georeferencing.

I implemented that already, but need to change some things and will push it next week.

**Comment by der-stefan** [comment]
Here is an example map for a coverage prediction map: [testmap.zip](https://github.com/hoche/splat/files/4249968/testmap.zip)

Just unzip the folder and open the html file locally in your webbrowser.

**Comment by davidsrsb** [comment]
I tried this with QGIS 3.10.2, which should understand GEOJSON and it rejected it.
Now I need to read up on the differences

**Comment by dBitech** [comment]
the json file included is not a geoJSON file.

**Comment by der-stefan** [comment]
Json is just a file format. You are free to put anything in any format in there, unless it follows the json specification. In my case I want to save any parameter that was used for the splat simulation. Perhaps it could also be read by splat for doing the same simulation again.

Please note that the file in the zip is not a native json file. It is wrapped by a callback function, since loading local json files in javascript is not possible.

**Comment by der-stefan** [comment]
The corona situation changed our whole life. We are now working from home, and the focus of the work changed. But we'll continue with Splat some day for sure!

**Comment by der-stefan** [comment]
Finally I started working on this feature again. My main task for now is a JSON output generator that can be used either for a complete documentation of all given arguments and parameters or for reading a georeferenced coverage image comfortably in Javascript. The branch is simply called "json".

**Comment by der-stefan** [comment]
Most of the json functionality is now there, but it should not be called from main(), but from the ImageWriter functions. Nonetheless, a complete set of all given parameters would also be interesting for non-coverage plots, as exactly the same simulation could be repeated by loading just this single json file.

**Comment by der-stefan** [comment]
I'm still struggling with the json file scheme, as the file should be of dual use:
- georeference the output image. Is it still necessary, as geotiffs are already georeferenced and pngs will be in the future, when I implement a simple metadata reference scheme?
- document all input parameters. Could be also read by splat for new simulations.

Give me some more time to present a new proposal...

**Comment by der-stefan** [comment]
Yeah, we need some functions for writing and reading JSON files. nlohmann/json provides all we need, but has more than 25 000 lines of code? :astonished: 
At least writing is not a big issue when using std::map. See json.cpp in the json branch. And I think a simple json parser can be accomplished within 100 lines...
I'll further work on the json feature. :+1:

**Comment by hoche** [comment]
I don't think it's a good idea to capture the raw input flags ("-hd", "-L", etc). It prevents you from ever changing those in the future. I would be in favor of using some predefined names for certain values  and putting those in the JSON, and then having the command lines be able to set those as well as an override. I would eventually like to get to the point where SPLAT! is just a library that can be called from a shell wrapper, or golang, or python, or CGI, or...

I do like the idea of being able to feed everything necessary to SPLAT! in one file. It might be nice to be able to refer to other files on disk though. For instance, you could either embed your TX site data in the JSON or provide a path to a file on the local disk.

 nlohmann's one-header library is pretty nice. Not the fastest thing, but pretty easy to use.

**Comment by dBitech** [comment]
maybe the "raw flags" is a misnomer, but to capture: {"high-definition": yes, "LOSplot": yes} where the key is the same as the variable name within the code.  The idea being, having the ability to generate a new plot with the same parameters as the original.

**Comment by watkipet** [comment]
> I don't think it's a good idea to capture the raw input flags ("-hd", "-L", etc). It prevents you from ever changing those in the future.

Take a look at the SplatRun class. That's supposed to encapsulate all the options for a run of Splat! Perhaps part of the JSON can be deserialized into that class?

**Comment by watkipet** [comment]
@der-stefan and @hoche - There are lot of improvements in the json branch that would be nice to merge into the refactor branch. Shall we merge the branches and create a new issue to "improve json support" since it might be awhile before json support is entirely finished?

**Comment by watkipet** [comment]
Closing issue. Will make a new issue, "Improve JSON support."
